# Generated by Django 3.2.9 on 2021-11-15 22:51

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.edit


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilAlunoUpdate',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
            ],
            bases=('auth.group', django.views.generic.edit.UpdateView),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='PerfilVoluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150, null=True)),
                ('cpf', models.CharField(max_length=14, null=True)),
                ('data_nasc', models.DateField(null=True)),
                ('contato', models.CharField(help_text='Digite apenas números com o DDD', max_length=11, null=True, verbose_name='Tel contato')),
                ('cidade', models.CharField(help_text='Digite sua cidade e Estado, EX: Campinas-SP', max_length=50, null=True)),
                ('nivel', models.CharField(choices=[('EMC', 'Ensino Médio'), ('ETC', 'Ensino Técnico'), ('ESC', 'Ensino Superior - cursando'), ('ESP', 'Ensino Superior - completo'), ('PGC', 'Pós-graduação - cursando'), ('PGP', 'Pós-graduação - completo')], max_length=3, null=True)),
                ('descricao', models.TextField(blank=True, help_text='Descreva um pouco da sua trajetória, as disciplinas que possui maior habilidade e como gostaria de ajudar nessa causa.', max_length=500, null=True, verbose_name='Descrição')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=50, null=True)),
                ('cpf', models.CharField(max_length=14, null=True)),
                ('data_nasc', models.DateField(null=True)),
                ('contato', models.CharField(help_text='Digite apenas números com o DDD', max_length=16, null=True, verbose_name='Tel contato')),
                ('cidade', models.CharField(help_text='Digite sua cidade e Estado, EX: Campinas-SP', max_length=50, null=True)),
                ('categoria', models.CharField(choices=[('AL', 'Aluno'), ('VT', 'Voluntário')], max_length=2, null=True)),
                ('serie', models.CharField(choices=[('5', '5ª Série'), ('6', '6ª Série'), ('7', '7ª Série'), ('8', '8ª Série'), ('9', '9ª Série')], max_length=1, null=True)),
                ('descricao', models.TextField(blank=True, help_text='Conte um pouco sobre você, em quais disciplinas estão suas dificuldades e como gostaria de ser ajudado.', max_length=500, null=True, verbose_name='Descrição')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
