# Generated by Django 3.2.9 on 2021-11-17 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_perfilaluno_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilvoluntario',
            name='nivel',
            field=models.CharField(choices=[('Ensino Médio', 'Ensino Médio'), ('Ensino Técnico', 'Ensino Técnico'), ('Ensino Superior - cursando', 'Ensino Superior - cursando'), ('Ensino Superior - completo', 'Ensino Superior - completo'), ('Pós-graduação - cursando', 'Pós-graduação - cursando'), ('Pós-graduação - completo', 'Pós-graduação - completo')], max_length=30, null=True),
        ),
    ]
