# Generated by Django 3.2.9 on 2021-11-19 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_perfilvoluntario_nivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilaluno',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='perfilaluno',
            name='cpf',
            field=models.CharField(max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='perfilaluno',
            name='data_nasc',
            field=models.DateField(null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='perfilaluno',
            name='serie',
            field=models.CharField(choices=[('1', '1º Ano'), ('2', '2º Ano'), ('3', '3º Ano')], max_length=1, null=True, verbose_name='Série'),
        ),
        migrations.AlterField(
            model_name='perfilvoluntario',
            name='cpf',
            field=models.CharField(max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='perfilvoluntario',
            name='data_nasc',
            field=models.DateField(null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='perfilvoluntario',
            name='nivel',
            field=models.CharField(choices=[('Ensino Médio', 'Ensino Médio'), ('Ensino Técnico', 'Ensino Técnico'), ('Ensino Superior - cursando', 'Ensino Superior - cursando'), ('Ensino Superior - completo', 'Ensino Superior - completo'), ('Pós-graduação - cursando', 'Pós-graduação - cursando'), ('Pós-graduação - completo', 'Pós-graduação - completo')], max_length=30, null=True, verbose_name='Nível'),
        ),
    ]
