# Generated by Django 3.2.9 on 2021-11-15 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('data_nasc', models.DateField()),
                ('contato', models.CharField(help_text='Digite apenas números com o DDD', max_length=11, verbose_name='Tel contato')),
                ('cidade', models.CharField(help_text='Digite sua cidade e Estado, EX: Campinas-SP', max_length=50)),
                ('nivel', models.CharField(choices=[('EMC', 'Ensino Médio'), ('ETC', 'Ensino Técnico'), ('ESC', 'Ensino Superior - cursando'), ('ESP', 'Ensino Superior - completo'), ('PGC', 'Pós-graduação - cursando'), ('PGP', 'Pós-graduação - completo')], max_length=3)),
                ('descricao', models.TextField(help_text='Descreva um pouco da sua trajetória, as disciplinas que possui maior habilidade e como gostaria de ajudar nessa causa.', max_length=500, verbose_name='Descrição')),
                ('usuario', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('data_nasc', models.DateField()),
                ('contato', models.CharField(help_text='Digite apenas números com o DDD', max_length=11, verbose_name='Tel contato')),
                ('cidade', models.CharField(help_text='Digite sua cidade e Estado, EX: Campinas-SP', max_length=50)),
                ('descricao', models.TextField(help_text='Conte um pouco sobre você, em quais disciplinas estão suas dificuldades e como gostaria de ser ajudado.', max_length=500, verbose_name='Descrição')),
                ('usuario', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
