# Generated by Django 3.2.9 on 2021-11-16 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Digite um nome curto para sua oferta de reforço', max_length=30)),
                ('nivel', models.CharField(choices=[('EMC', 'Ensino Médio'), ('ETC', 'Ensino Técnico'), ('ESC', 'Ensino Superior - cursando'), ('ESP', 'Ensino Superior - completo'), ('PGC', 'Pós-graduação - cursando'), ('PGP', 'Pós-graduação - completo')], help_text='Selecione seu nível de instrução', max_length=3)),
                ('area', models.CharField(choices=[('MA', 'Matemática'), ('PO', 'Língua Portuguesa'), ('GE', 'Geografia'), ('HI', 'História'), ('FI', 'Física'), ('QI', 'Química'), ('BI', 'Biologia'), ('AR', 'Artes'), ('EF', 'Educação Física'), ('SO', 'Sociologia'), ('FI', 'Filosofia'), ('IN', 'Inglês'), ('OU', 'Outras')], help_text='Selecione uma área do conhecimento', max_length=2)),
                ('descricao', models.TextField(help_text='Escreva livremente com detalhes suas habilidades e como pode ajudar um aluno.', max_length=250)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dificuldade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Digite um nome curto para sua dificuldade', max_length=30)),
                ('area', models.CharField(choices=[('MA', 'Matemática'), ('PO', 'Língua Portuguesa'), ('GE', 'Geografia'), ('HI', 'História'), ('FI', 'Física'), ('QI', 'Química'), ('BI', 'Biologia'), ('AR', 'Artes'), ('EF', 'Educação Física'), ('SO', 'Sociologia'), ('FI', 'Filosofia'), ('IN', 'Inglês'), ('OU', 'Outras')], help_text='Selecione uma área do conhecimento', max_length=2)),
                ('assunto', models.CharField(help_text='Assunto(s) dentro da área do conhecimento. Ex: Equação do Segundo Grau, Equação do Primeiro Grau e Frações', max_length=200)),
                ('descricao', models.TextField(help_text='Escreva livremente com detalhes quais suas dificuldades e como o voluntário pode te ajudar', max_length=250)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
