# Generated by Django 3.2.9 on 2021-11-16 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_dificuldade_oferta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dificuldade',
            name='area',
            field=models.CharField(choices=[('Matemática', 'Matemática'), ('Língua Portuguesa', 'Língua Portuguesa'), ('Geografia', 'Geografia'), ('História', 'História'), ('Física', 'Física'), ('Química', 'Química'), ('Biologia', 'Biologia'), ('Artes', 'Artes'), ('Educação Física', 'Educação Física'), ('Sociologia', 'Sociologia'), ('Filosofia', 'Filosofia'), ('Inglês', 'Inglês'), ('Outras', 'Outras')], help_text='Selecione uma área do conhecimento', max_length=20),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='area',
            field=models.CharField(choices=[('Matemática', 'Matemática'), ('Língua Portuguesa', 'Língua Portuguesa'), ('Geografia', 'Geografia'), ('História', 'História'), ('Física', 'Física'), ('Química', 'Química'), ('Biologia', 'Biologia'), ('Artes', 'Artes'), ('Educação Física', 'Educação Física'), ('Sociologia', 'Sociologia'), ('Filosofia', 'Filosofia'), ('Inglês', 'Inglês'), ('Outras', 'Outras')], help_text='Selecione uma área do conhecimento', max_length=20),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='nivel',
            field=models.CharField(choices=[('Ensino Médio', 'Ensino Médio'), ('Ensino Técnico', 'Ensino Técnico'), ('Ensino Superior - cursando', 'Ensino Superior - cursando'), ('Ensino Superior - completo', 'Ensino Superior - completo'), ('Pós-graduação - cursando', 'Pós-graduação - cursando'), ('Pós-graduação - completo', 'Pós-graduação - completo')], help_text='Selecione seu nível de instrução', max_length=30),
        ),
    ]
