# Generated by Django 3.2.9 on 2021-11-17 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20211116_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='nivel',
        ),
        migrations.AddField(
            model_name='oferta',
            name='habilidade',
            field=models.CharField(choices=[('Iniciante', 'Iniciante'), ('Intermediário', 'Intermediário'), ('Avançado', 'Avançado')], default='Iniciante', help_text='Selecione o nível de habilidade para a oferta que está registrando', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dificuldade',
            name='area',
            field=models.CharField(choices=[('Matemática', 'Matemática'), ('Língua Portuguesa', 'Língua Portuguesa'), ('Geografia', 'Geografia'), ('História', 'História'), ('Física', 'Física'), ('Química', 'Química'), ('Biologia', 'Biologia'), ('Artes', 'Artes'), ('Educação Física', 'Educação Física'), ('Sociologia', 'Sociologia'), ('Filosofia', 'Filosofia'), ('Inglês', 'Inglês'), ('Outras', 'Outras')], help_text='Selecione uma área do conhecimento', max_length=20, verbose_name='Disciplina'),
        ),
        migrations.AlterField(
            model_name='dificuldade',
            name='nome',
            field=models.CharField(help_text='Digite um nome curto para sua dificuldade', max_length=30, verbose_name='Nome da dificuldade'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='nome',
            field=models.CharField(help_text='Digite um nome curto para sua oferta de reforço', max_length=30, verbose_name='Oferta de Reforço'),
        ),
    ]
