# Generated by Django 3.2.9 on 2021-11-20 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211118_2309'),
        ('registration', '0005_auto_20211118_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagensaluno',
            name='receiver',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.perfilaluno'),
        ),
        migrations.AlterField(
            model_name='mensagensvoluntario',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.dificuldade'),
        ),
    ]
