# Generated by Django 3.2.9 on 2021-11-20 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_alter_mensagensaluno_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagensaluno',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='registration.dificuldade'),
        ),
    ]
