# Generated by Django 3.2.9 on 2021-11-20 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_auto_20211118_2309'),
        ('registration', '0010_alter_mensagensaluno_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagensaluno',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mensagensvoluntario',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.perfilvoluntario'),
        ),
    ]
